name: 'Deploy EC2 and configure with Ansible'
on:
  workflow_dispatch:
    inputs:
      jobs:
        description: 'Job to run'
        type: choice
        options:
          - 'plan'
          - 'apply'
          - 'destroy'

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          mkdir -p ~/.aws   
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
          echo "region=${AWS_DEFAULT_REGION}" >> ~/.aws/credentials

      - name: terraform init
        run: terraform init

      - name: terraform plan
        run: terraform plan

      - name: terraform apply
        if: github.event.inputs.jobs == 'apply'
        run: terraform apply -auto-approve

      - name: terraform destroy
        if: github.event.inputs.jobs == 'destroy'
        run: terraform destroy -auto-approve

      - name: Get EC2 ipadress
        id: get_ip
        working-directory: ./terraform
        run: echo "INSTANCE_IP=$(terraform output -raw instance_ip)" >> $GITHUB_ENV

      - name: Setup Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Create Ansible Inventory
        run: |
          echo "[localhost]" > ./ansible/inventory
          echo "${{ env.INSTANCE_IP }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/my-key.pem" >> ansible/inventory.ini
      
      - name: Run Ansible playbook
        run: ansible-playbook -i ./ansible/inventory ./ansible/playbook.yml