name: Deploy RustDesk Infrastructure
on:
  workflow_dispatch:
    inputs:
      tf_action:
        description: 'Terraform action (apply/destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

env:
  AWS_REGION: "us-west-1"
  ANSIBLE_USER: "ubuntu"
  

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init 

      - name: Terraform Validate
        run: terraform validate 

      - name: Terraform Plan/Apply/Destroy
        run: |
          if [ "${{ github.event.inputs.tf_action }}" == "apply" ]; then
            terraform plan 
            terraform apply -auto-approve 
          else
            terraform destroy -auto-approve 
          fi

      
      - name: Get EC2 IP
        if: github.event.inputs.tf_action == 'apply'
        id: ec2_ip
        run: |
          IP=$(terraform output -raw instance_ip 2>/dev/null | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
          echo "ec2_ip=${IP}" >> "$GITHUB_ENV"
        shell: bash
      
  

  ansible-deploy:
    name: Ansible Deployment
    runs-on: ubuntu-latest
    needs: [terraform]
    if: github.event.inputs.tf_action == 'apply'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH to EC2    
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          #get the hostname from the ec2_ip after add it to $GITHUB_ENV above
          HOSTNAME: ${{ env.ec2_ip }}

          USER_NAME: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ubuntu &&
              sudo apt-get update && sudo apt-get install -y ansible
              #run ansible playbook by using the file in the repo in the ansible folder
              ansible-playbook ansible/playbook.yml -i "${{ env.ec2_ip }}," -u ubuntu --private-key ~/.ssh/id_rsa
              '

      