name: Deploy RustDesk Infrastructure
on:
  workflow_dispatch:
    inputs:
      tf_action:
        description: 'Terraform action (apply/destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

env:
  AWS_REGION: "us-west-1"
  ANSIBLE_USER: "ubuntu"

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init 

      - name: Terraform Validate
        run: terraform validate 

      - name: Terraform Plan/Apply/Destroy
        run: |
          if [ "${{ github.event.inputs.tf_action }}" == "apply" ]; then
            terraform plan 
            terraform apply -auto-approve 
          else
            terraform destroy -auto-approve 
          fi

      - name: Get EC2 IP
        if: github.event.inputs.tf_action == 'apply'
        id: ec2_ip
        run: |
          IP=$(terraform output -raw instance_ip 2>/dev/null | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
          echo "ec2_ip=${IP}" << EOF
          echo EOF
          >> "$GITHUB_ENV"
        shell: bash

  